.\" Process this file with
.\" groff -Tascii -man /path/tosource/installpkg.1 > outputfile.1
.\"
.TH INSTALLPKG 1 "1 November 2011"
.SH NAME
installpkg - allows quick installation of multiple packages.
.SH SYNOPSIS
installpkg <package1.pkg> [package2.pkg]...etc
.SH DESCRIPTION
.B
INSTALLPKG
attempts to install packages passed in as argument(s) 
If the items file name ends in .pkg or .mpkg installation will be attempted.

Flag summary : 
 -i		install from disk image
 -h		hide mount point of disk iamge (only works with the -i flag)
 -u		install from URL
 -c		copy to local storage before installing (incompatible with -u flag)
 -q		quiet output (less verbose)
 
It is possible to use the -i flag to install all the packages in 
root level of a .dmg file. In addition it is possible to use the -u
flag to specify installation of a flat package from a specified
URL (downloaded with wget). Usage of the -h flag will result in
mounting to a temporary location and also for the mount point to 
be hiden from the Finder. The -c flag will result in all specifed 
files being copied to a local storage area prior to being installed.

Combinations of various flags are also possible and encouraged.

Usage Examples :

   installpkg package1.pkg package2.pkg

   installpkg /directory_full_of_pacakges/*

   installpkg -i image1.dmg image2.dmg

   installpkg -i /directory_full_of_images/*
   
   installpkg -iu http://lucid.systems/download/installpkg
   
   installpkg -iuh http://lucid.systems/download/installpkg
   
   installpkg -u http://pkgserver.example.com/mypackage.pkg

   installpkg -ih image1.dmg image2.dmg
   
   installpkg -ihc image1.dmg image2.dmg
   

.SH BUGS
(1)
The name is not very good.

(2)
This software is not very well tested, please report any issues.

(3)
InstallPKG is not very configurable.


.SH AUTHOR
Henri Shustak, Leif Keane

installpkg is protected by various licenses agreements.

Check http://lucidsystems.org for further details.

InstallPKG website : http://www.lucid.technology/tools/installpkg

.SH "SEE ALSO"
.BR installer (1),
.BR bash (1),
.BR grep (1),
.BR defaults (1),
.BR basename (1),
.BR echo (1),
.BR killall (1),
.BR tail (1),
.BR awk (1)
.BR rsync (1)
.BR wget (1)